//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public int Id { get; set; }
        public string NameOfTeam { get; set; }
        public string NameOfLeague { get; set; }
        public Nullable<int> BasketballClubId { get; set; }
        public Nullable<int> LeagueId { get; set; }
    
        public virtual BasketballClub BasketballClub { get; set; }
        public virtual League League { get; set; }
    }
}
