//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerPosition
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int PositionId { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Position Position { get; set; }
    }
}
